name: "✍️ ​ ​Suggest Bitcoin Roadmap Changes"
description: Help us improve the Bitcoin roadmap by suggesting changes
labels: [suggestion]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the Bitcoin roadmap with your suggestions.
  - type: input
    id: title
    attributes:
      label: Title
      description: Please provide a title for your suggestion.
      placeholder: Enter a title for your suggestion.
    validations:
      required: true
  - type: textarea
    id: roadmap-suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest for the Bitcoin roadmap?
      placeholder: Enter your suggestions here.
    validations:
      required: true
